### ISSUE TITLE
Autocompletion for TS

### ISSUE THREAD

**Issue by skanwal** [umccr/cwl-ica-cli#46]
The auto complete doesn’t work for me when using `cwl-ica append-typescript*` command using v1.2.5

**Comment by alexiswl** [comment]
Have you tried opening a new terminal and then doing this again? Could be that the autocompletion you're using was sourced from an older version of cwl-ica? Reloading your environment should resolve this.  

![append-typescript-autocompletion](https://user-images.githubusercontent.com/8197659/196845011-2ab71a6f-91ac-44fb-8c41-4a694f375086.gif)

**Comment by alexiswl** [comment]
@skanwal can you confirm this is resolved and close if so?

**Comment by skanwal** [comment]
yep - can confirm this was fixed in new session.
